In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"

In [2]:
import tensorflow as tf

In [11]:
# Initialization of a tensors
x = tf.constant(4, shape=(3,5), dtype=tf.float32)
y = tf.constant([[1,2,3], [4,5,6]])
z = tf.ones((3, 3))
w = tf.eye(3, dtype=tf.int32)
print(x, y, z, w, end="\n")

tf.Tensor(
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]], shape=(3, 5), dtype=float32) tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [18]:
# Mathematical operations
x = tf.constant([1, 2, 3])
y = tf.constant([9 , 8, 7])
sum_ = tf.add(x, y)  # or x + y
difference = tf.subtract(x, y)  # or x - y
prod = tf.multiply(x, y)  #  or x * y
division = tf.divide(x, y)  #  or x / y
dot_product = tf.tensordot(x, y, axes=1)
print(sum_, difference, prod, division, end="\n")

tf.Tensor([10 10 10], shape=(3,), dtype=int32) tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32) tf.Tensor([ 9 16 21], shape=(3,), dtype=int32) tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [34]:
# Reshaping
x = tf.range(9)
reshape1 = tf.reshape(x, shape=(3, 3))

y = tf.range(6, 0, -1)
reshape2 = tf.reshape(y, (3, 2))


In [35]:
print(reshape1)
print(reshape2)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[6 5]
 [4 3]
 [2 1]], shape=(3, 2), dtype=int32)
